Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -187,13 +187,25 @@ jobs:
           rollback_deployment() {
             local error_message=$1
             echo "$error_message Rolling back to version ${{ env.LAST_SUCCESSFUL_VERSION }}"
+            docker compose down --remove-orphans
+            docker system prune -f
             docker pull ${{ secrets.DOCKER_USERNAME }}/booking_nginx:${{ env.LAST_SUCCESSFUL_VERSION }}
             docker pull ${{ secrets.DOCKER_USERNAME }}/booking_app:${{ env.LAST_SUCCESSFUL_VERSION }}
             echo "TAG=${{ env.LAST_SUCCESSFUL_VERSION }}" > .env
             echo "DOCKER_HUB_NICKNAME=${{ secrets.DOCKER_HUB_NICKNAME }}" >> ~/project/.env
             docker compose up -d --force-recreate
+
+            echo "ROLLBACK_PERFORMED=true" >> rollback_status
+                
             exit 1
           }
+
+          # Проверяем был ли выполнен rollback
+          if [ -f rollback_status ]; then
+            rm rollback_status
+            echo "::set-output name=rollback::true"
+            exit 1
+          fi
 
           # Check deployment status
           if [ $? -ne 0 ]; then
@@ -226,12 +238,19 @@ jobs:
             git push
         
     - name: Exit workflow after rollback
-      if: failure() && steps.deploy_step.outcome == 'failure'
+      if: |
+        always() && 
+        (steps.deploy_step.outcome == 'failure' || 
+         steps.deploy_step.outputs.rollback == 'true')
       run: |
-            echo "Deployment failed and rollback was performed. Stopping workflow."
-            exit 1
+        echo "Deployment failed or rollback was performed. Stopping workflow."
+        exit 1
 
     - name: SSL Certificate Management
+      if: |
+        success() && 
+        steps.deploy_step.outcome == 'success' && 
+        steps.deploy_step.outputs.rollback != 'true'
       uses: appleboy/ssh-action@v0.1.5
       with:
         host: ${{ secrets.AWS_SERVER_IP }}
